apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: expense
  labels:
    project: expense
    component: frontend
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: frontend
      tier: web
  template:
    metadata:
      labels:
        project: expense
        component: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: avinbandela/frontend:v1.0
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: frontend
    tier: web
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80

