apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespce: expense
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: avinbandela/mysql:v1.0

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
